### ISSUE TITLE
Feat: Create `dart` implementation of `multihash` for use in `dart_cid`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dart_multihash#1]
As noted in [/dwyl/learn-ipfs](https://github.com/dwyl/learn-ipfs#what-are-centralised-decentralised-and-distributed-networks-) we believe that ***distributed*** networks are the future. 
At the time of writing there is no **`dart`** implementation of `multihash` listed in: [github.com/multiformats/multihash/#implementations](https://github.com/multiformats/multihash/tree/df0cf2dc0542e732f882fd238df257abe22f2a78#implementations)

Our objective is to create one so that we can use it in our [**`Flutter`** Project](https://github.com/dwyl/product-roadmap/issues/40).
Putting in the effort up-front to do create a well-documented, tested & maintained package 
will help save other people building "[DApps](https://en.wikipedia.org/wiki/Decentralized_application)" time.

# Todo ✅ 

+ [x] Create World Class Documentation for how to _use_ `dart_multihash` in a `dart` or `Flutter` project _up-front_. 📝 
   + [x] This _could_ include a **_basic_ `Flutter` App** similar to https://github.com/dwyl/flutter-counter-example
    ***or*** just have an `/examples` directory within this repo. Your pick! 💻 
+ [x] Write tests for the function with reference to the `Go`, `Rust` or `JS` implementation (a known working example) 🧪 
+ [x] Implement the `code` with all `dart` best practices for inline docs 🧑‍💻 
+ [x] Publish the package to `pub.dev` under the `@dwyl` namespace/ownership for business continuity. 📦 
+ [x] Open Pull Request to https://github.com/multiformats/multihash#implementations to add to list 🚀 

> **Note**: it's not a truly Decentralised App if people have to get it from a proprietary App Store ... but you get the idea. 💭

https://pub.dev/packages/multihash
<img width="921" alt="image" src="https://user-images.githubusercontent.com/194400/204019233-d42da6b7-ed99-4e41-8689-6e09deb47d41.png">

https://pub.dev/packages?q=multihash
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/194400/204018980-211780b1-ed03-4dce-bbd4-a6b6669ff7a4.png">

**Comment by nelsonic** [comment]
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/194400/204018980-211780b1-ed03-4dce-bbd4-a6b6669ff7a4.png">

**Comment by nelsonic** [comment]
@LuchoTurtle the package should be called just `multihash` not `dart_multihash`
We don't need the word `dart` in any of the filenames:

```
dart pub publish --dry-run

Publishing dart_multihash 0.0.1 to https://pub.dartlang.org:
|-- .github
|   '-- ci.yml
|-- .gitignore
|-- CHANGELOG.md
|-- LICENSE
|-- README.md
|-- analysis_options.yaml
|-- dart_multihash.iml
|-- lib
|   |-- dart_multihash.dart
|   '-- src
|       |-- constants.dart
|       |-- models.dart
|       '-- varintUtils.dart
|-- pubspec.yaml
'-- test
    |-- dart_multihash_test.dart
    '-- dart_varint_test.dart
```

Please rename `lib/dart_multihash.dart` to `lib/multihash.dart` etc. (_before we publish to `pub.dev`..._) 🙏

**Comment by LuchoTurtle** [comment]
We shouldn't change it to `multihash` because we should follow [the multiformat's convention](https://github.com/multiformats/multihash#implementations). Every implementation has the language suffixed and I believe we should maintain this so we could successfully add our own to the list.

**Comment by nelsonic** [comment]
Good spot. 👍 
Reluctantly. Agree. 👌 
Please feel free to publish so you can continue making progress. :shipit: 
Then when you feel it's "stable" (V1.0), transfer to the newly created @dwyl verified publisher https://github.com/dwyl/learn-dart/issues/22#issuecomment-1331443016 📦

**Comment by nelsonic** [comment]
@LuchoTurtle if you need to push directly to `main` to figure out the `CI` please do it. :shipit: 
This project is in "setup phase" so it's acceptable. 🔧 
Once it's published we will [**protect `main` branch**](https://github.com/dwyl/protect-main-branch) to avoid destruction. 🔥

**Comment by LuchoTurtle** [comment]
The package [has been published](https://pub.dev/packages/dart_multihash) and a [PR has been opened to add it to the `multiformats` canonical repo](https://github.com/multiformats/multihash/pull/154).
Submitting for review so @nelsonic can close it.

**Comment by nelsonic** [comment]
@LuchoTurtle stoked you got your implementation published and PR adding it to the list merged. 🎉

**Comment by nelsonic** [comment]
Well done again. 🙌
